### ISSUE TITLE
The type or namespace name 'Fasterflect' could not be found (are you missing a using directive or an assembly reference?) 

### ISSUE THREAD

**Issue by CyanPrime** [BoomaNation/Booma.Library#2] opened 2017-05-15 17:16 UTC
Hi, So I'm trying to build this, and these are the steps I've taken:
1)Fork repo
2)install Github extention for VS2017
3)Clone my fork (Of this repo)
4)Clicked on Booma.Library solution file to open the solution.
5)Go to Tools > Nuget Package Manager > Package Manager Settings >Package Sources and hit the plus sign to create a new package source. Input https://www.myget.org/F/hellokitty/api/v2 as the source (with PSOR as the name) and hit update.
6) go to Tools > Nuget Package Manager > Manage Nuget Packages for Salution > Hit Restore in the yellow box ( in the Manage Nuget Packages for Salution tab)
7) hit build 

And this is my build output:
1>------ Build started: Project: Booma.Entity.Identity, Configuration: Debug Any CPU ------
2>------ Build started: Project: Booma.Payloads.Common, Configuration: Debug Any CPU ------
3>------ Build started: Project: Booma.Payloads.Surrogates.Unity, Configuration: Debug Any CPU ------
4>------ Build started: Project: Booma.Stats.Common, Configuration: Debug Any CPU ------
2>  Booma.Payloads.Common -> D:\PSOR\Booma.Library\src\Booma.Payloads.Common\bin\Debug\Booma.Payloads.Common.dll
3>  Booma.Payloads.Surrogates.Unity -> D:\PSOR\Booma.Library\src\Booma.Payloads.Surrogates.Unity\bin\Debug\Booma.Payloads.Surrogates.Unity.dll
1>  Booma.Entity.Identity -> D:\PSOR\Booma.Library\src\Booma.Entity.Identity\bin\Debug\Booma.Entity.Identity.dll
5>------ Build started: Project: Booma.Unity.Network.Client, Configuration: Debug Any CPU ------
6>------ Build started: Project: Booma.Instance.NetworkObject, Configuration: Debug Any CPU ------
7>------ Build started: Project: Booma.Payloads.Instance, Configuration: Debug Any CPU ------
4>  Booma.Stats.Common -> D:\PSOR\Booma.Library\src\Booma.Stats.Common\bin\Debug\Booma.Stats.Common.dll
8>------ Build started: Project: Booma.ServerSelection.Common, Configuration: Debug Any CPU ------
8>  Booma.ServerSelection.Common -> D:\PSOR\Booma.Library\src\Booma.ServerSelection.Common\bin\Debug\Booma.ServerSelection.Common.dll
9>------ Build started: Project: Booma.Payloads.ServerSelection, Configuration: Debug Any CPU ------
9>  Booma.Payloads.ServerSelection -> D:\PSOR\Booma.Library\src\Booma.Payloads.ServerSelection\bin\Debug\Booma.Payloads.ServerSelection.dll
10>------ Build started: Project: Booma.Unity.Network.Server, Configuration: Debug Any CPU ------
5>D:\PSOR\Booma.Library\src\Booma.Unity.Network.Client\Peer\BoomaNetworkWebPeer.cs(57,40,57,48): warning CS0649: Field 'BoomaNetworkWebPeer<TInheritingType>.registry' is never assigned to, and will always have its default value null
5>D:\PSOR\Booma.Library\src\Booma.Unity.Network.Client\Peer\PeerEndpointDetails.cs(22,18,22,30): warning CS0649: Field 'PeerEndpointDetails.endpointName' is never assigned to, and will always have its default value null
5>D:\PSOR\Booma.Library\src\Booma.Unity.Network.Client\Peer\PeerEndpointDetails.cs(36,18,36,33): warning CS0649: Field 'PeerEndpointDetails.applicationName' is never assigned to, and will always have its default value null
5>D:\PSOR\Booma.Library\src\Booma.Unity.Network.Client\Peer\PeerEndpointDetails.cs(29,15,29,27): warning CS0649: Field 'PeerEndpointDetails.endpointPort' is never assigned to, and will always have its default value 0
5>D:\PSOR\Booma.Library\src\Booma.Unity.Network.Client\Peer\BoomaNetworkWebPeer.cs(29,18,29,25): warning CS0649: Field 'BoomaNetworkWebPeer<TInheritingType>.BaseUrl' is never assigned to, and will always have its default value null
5>  Booma.Unity.Network.Client -> D:\PSOR\Booma.Library\src\Booma.Unity.Network.Client\bin\Debug\Booma.Unity.Network.Client.dll
10>D:\PSOR\Booma.Library\src\Booma.Unity.Network.Server\BoomaServerApplicationBase.cs(27,25,27,32): warning CS0649: Field 'BoomaServerApplicationBase._Logger' is never assigned to, and will always have its default value null
10>  Booma.Unity.Network.Server -> D:\PSOR\Booma.Library\src\Booma.Unity.Network.Server\bin\Debug\Booma.Unity.Network.Server.dll
11>------ Build started: Project: Booma.Instance.Anim, Configuration: Debug Any CPU ------
12>------ Build started: Project: Booma.Instance.Common, Configuration: Debug Any CPU ------
11>  Booma.Instance.Anim -> D:\PSOR\Booma.Library\src\Booma.Instance.Anim\bin\Debug\Booma.Instance.Anim.dll
13>------ Build started: Project: Booma.ServerSelection.Client, Configuration: Debug Any CPU ------
6>  Booma.Instance.NetworkObject -> D:\PSOR\Booma.Library\src\Booma.Instance.NetworkObject\bin\Debug\Booma.Instance.NetworkObject.dll
14>------ Build started: Project: Booma.Instance.NetworkObject.Objects, Configuration: Debug Any CPU ------
12>D:\PSOR\Booma.Library\src\Booma.Instance.Common\Entity\Spawn\Player\NetworkPlayerEntityFactory.cs(29,40,29,59): warning CS0649: Field 'NetworkPlayerEntityFactory.playerSpawnStrategy' is never assigned to, and will always have its default value null
12>D:\PSOR\Booma.Library\src\Booma.Instance.Common\Entity\Prefab\EntityPrefabProvider.cs(15,22,15,39): warning CS0649: Field 'EntityPrefabProvider.LocalPlayerPrefab' is never assigned to, and will always have its default value null
12>D:\PSOR\Booma.Library\src\Booma.Instance.Common\Entity\Prefab\EntityPrefabProvider.cs(19,22,19,41): warning CS0649: Field 'EntityPrefabProvider.NetworkPlayerPrefab' is never assigned to, and will always have its default value null
12>D:\PSOR\Booma.Library\src\Booma.Instance.Common\Entity\Spawn\Player\NetworkPlayerEntityFactory.cs(23,33,23,47): warning CS0649: Field 'NetworkPlayerEntityFactory.prefabProvider' is never assigned to, and will always have its default value null
12>D:\PSOR\Booma.Library\src\Booma.Instance.Common\Entity\Spawn\Player\NetworkPlayerEntityFactory.cs(35,39,35,56): warning CS0649: Field 'NetworkPlayerEntityFactory.gameobjectFactory' is never assigned to, and will always have its default value null
12>  Booma.Instance.Common -> D:\PSOR\Booma.Library\src\Booma.Instance.Common\bin\Debug\Booma.Instance.Common.dll
15>------ Build started: Project: Booma.Combat.Formula.Server, Configuration: Debug Any CPU ------
14>D:\PSOR\Booma.Library\src\Booma.Instance.NetworkObject.Objects\Objects\NetworkButton.cs(34,22,34,31): warning CS0649: Field 'NetworkButton.OnPressed' is never assigned to, and will always have its default value null
14>D:\PSOR\Booma.Library\src\Booma.Instance.NetworkObject.Objects\Objects\NetworkButton.cs(31,22,31,35): warning CS0649: Field 'NetworkButton.OnDeactivated' is never assigned to, and will always have its default value null
14>D:\PSOR\Booma.Library\src\Booma.Instance.NetworkObject.Objects\Objects\NetworkDoor.cs(21,22,21,36): warning CS0649: Field 'NetworkDoor.onDoorUnlocked' is never assigned to, and will always have its default value null
14>D:\PSOR\Booma.Library\src\Booma.Instance.NetworkObject.Objects\State\NetworkEntityStateTag.cs(31,33,31,47): warning CS0649: Field 'NetworkEntityStateTag<TStateType>.OnStateChanged' is never assigned to, and will always have its default value null
14>D:\PSOR\Booma.Library\src\Booma.Instance.NetworkObject.Objects\State\NetworkEntityStateTag.cs(37,22,37,34): warning CS0649: Field 'NetworkEntityStateTag<TStateType>.defaultState' is never assigned to, and will always have its default value
14>  Booma.Instance.NetworkObject.Objects -> D:\PSOR\Booma.Library\src\Booma.Instance.NetworkObject.Objects\bin\Debug\Booma.Instance.NetworkObject.Objects.dll
16>------ Build started: Project: Booma.Unity.Logging.Common, Configuration: Debug Any CPU ------
7>  Booma.Payloads.Instance -> D:\PSOR\Booma.Library\src\Booma.Payloads.Instance\bin\Debug\Booma.Payloads.Instance.dll
17>------ Build started: Project: Booma.Unity.Network.IoCModules.Common, Configuration: Debug Any CPU ------
13>CSC : error CS0006: Metadata file 'D:\PSOR\Booma.Library\src\Booma.Unity.Network.Common\bin\Debug\Booma.Unity.Network.Common.dll' could not be found
18>------ Build started: Project: Booma.Instance.Client, Configuration: Debug Any CPU ------
16>  Booma.Unity.Logging.Common -> D:\PSOR\Booma.Library\src\Booma.Unity.Logging.Common\bin\Debug\Booma.Unity.Logging.Common.dll
19>------ Build started: Project: Booma.Instance.Server, Configuration: Debug Any CPU ------
17>  Booma.Unity.Network.IoCModules.Common -> D:\PSOR\Booma.Library\src\Booma.Unity.Network.IoCModules.Common\bin\Debug\Booma.Unity.Network.IoCModules.Common.dll
15>  Booma.Combat.Formula.Server -> D:\PSOR\Booma.Library\src\Booma.Combat.Formula.Server\bin\Debug\Booma.Combat.Formula.Server.dll
20>------ Build started: Project: Booma.Entity.Character, Configuration: Debug Any CPU ------
21>------ Build started: Project: Booma.Unity.Network.Common, Configuration: Debug Any CPU ------
20>  Booma.Entity.Character -> D:\PSOR\Booma.Library\src\Booma.Entity.Character\bin\Debug\Booma.Entity.Character.dll
22>------ Build started: Project: Booma.Stats.Common.Tests, Configuration: Debug Any CPU ------
21>D:\PSOR\Booma.Library\src\Booma.Unity.Network.Common\RequestGenerator.cs(20,20,20,32): warning CS0649: Field 'RequestGenerator._NetworkPeer' is never assigned to, and will always have its default value null
21>  Booma.Unity.Network.Common -> D:\PSOR\Booma.Library\src\Booma.Unity.Network.Common\bin\Debug\Booma.Unity.Network.Common.dll
23>------ Build started: Project: Booma.Unity.Network.IoCModules.Client, Configuration: Debug Any CPU ------
22>  Booma.Stats.Common.Tests -> D:\PSOR\Booma.Library\test\Booma.Stats.Common.Tests\bin\Debug\Booma.Stats.Common.Tests.dll
24>------ Build started: Project: Booma.Unity.Network.IoCModules.Server, Configuration: Debug Any CPU ------
19>D:\PSOR\Booma.Library\src\Booma.Instance.Server\Networking\BoomaInstanceServerApplicationBase.cs(36,38,36,59): warning CS0649: Field 'BoomaInstanceServerApplicationBase.OnSessionDisconnected' is never assigned to, and will always have its default value null
19>D:\PSOR\Booma.Library\src\Booma.Instance.Server\Entity\Components\Broadcasting\AllPeerMessageBroadcastingStrategy.cs(18,44,18,49): warning CS0649: Field 'AllPeerMessageBroadcastingStrategy.peers' is never assigned to, and will always have its default value null
19>D:\PSOR\Booma.Library\src\Booma.Instance.Server\Entity\RoundRobinEntitySpawnLocationProvider.cs(17,23,17,43): warning CS0649: Field 'RoundRobinEntitySpawnLocationProvider.SpawnPointTransforms' is never assigned to, and will always have its default value null
19>D:\PSOR\Booma.Library\src\Booma.Instance.Server\Entity\NetworkEntitySceneCollector.cs(20,44,20,60): warning CS0649: Field 'NetworkEntitySceneCollector.entityCollection' is never assigned to, and will always have its default value null
19>D:\PSOR\Booma.Library\src\Booma.Instance.Server\Entity\Components\Broadcasting\Common\PlayerSpawnBroadcaster.cs(29,29,29,33): warning CS0649: Field 'PlayerSpawnBroadcaster.peer' is never assigned to, and will always have its default value null
19>D:\PSOR\Booma.Library\src\Booma.Instance.Server\Entity\Components\Broadcasting\NetworkMessageBroadcaster.cs(53,58,53,74): warning CS0649: Field 'NetworkMessageBroadcaster.componentFactory' is never assigned to, and will always have its default value null
19>D:\PSOR\Booma.Library\src\Booma.Instance.Server\Entity\Components\Broadcasting\Common\EntityStateChangeBroadcaster.cs(19,32,19,45): warning CS0649: Field 'EntityStateChangeBroadcaster.guidContainer' is never assigned to, and will always have its default value null
19>D:\PSOR\Booma.Library\src\Booma.Instance.Server\Entity\Components\Broadcasting\Common\PlayerSpawnBroadcaster.cs(23,32,23,45): warning CS0649: Field 'PlayerSpawnBroadcaster.guidContainer' is never assigned to, and will always have its default value null
19>D:\PSOR\Booma.Library\src\Booma.Instance.Server\Networking\BoomaInstanceServerApplicationBase.cs(24,73,24,116): warning CS0649: Field 'BoomaInstanceServerApplicationBase.instanceSessionRequestMessageHandlerService' is never assigned to, and will always have its default value null
19>D:\PSOR\Booma.Library\src\Booma.Instance.Server\Networking\BoomaInstanceServerApplicationBase.cs(30,36,30,55): warning CS0649: Field 'BoomaInstanceServerApplicationBase.OnNewSessionCreated' is never assigned to, and will always have its default value null
19>D:\PSOR\Booma.Library\src\Booma.Instance.Server\Entity\Components\Tags\ServerGameObjectEntityIdentityTag.cs(15,40,15,51): warning CS0649: Field 'ServerGameObjectEntityIdentityTag.guidFactory' is never assigned to, and will always have its default value null
19>D:\PSOR\Booma.Library\src\Booma.Instance.Server\Entity\Components\Broadcasting\NetworkMessageBroadcaster.cs(45,42,45,58): warning CS0649: Field 'NetworkMessageBroadcaster.broadcastingMode' is never assigned to, and will always have its default value
19>D:\PSOR\Booma.Library\src\Booma.Instance.Server\Entity\Components\Broadcasting\Common\PlayerSpawnBroadcaster.cs(26,44,26,60): warning CS0649: Field 'PlayerSpawnBroadcaster.entityCollection' is never assigned to, and will always have its default value null
19>D:\PSOR\Booma.Library\src\Booma.Instance.Server\Entity\Components\Broadcasting\Common\NetworkTransformBroadcaster.cs(66,21,66,36): warning CS0649: Field 'NetworkTransformBroadcaster.entityTransform' is never assigned to, and will always have its default value null
19>D:\PSOR\Booma.Library\src\Booma.Instance.Server\Entity\Components\Broadcasting\Common\PlayerSpawnBroadcaster.cs(20,21,20,36): warning CS0649: Field 'PlayerSpawnBroadcaster.entityTransform' is never assigned to, and will always have its default value null
19>D:\PSOR\Booma.Library\src\Booma.Instance.Server\Entity\Components\Tags\GameObjectEntityPrefabTag.cs(16,28,16,36): warning CS0649: Field 'GameObjectEntityPrefabTag.prefabId' is never assigned to, and will always have its default value
19>D:\PSOR\Booma.Library\src\Booma.Instance.Server\Entity\Components\Broadcasting\IgnoreOwnerPeerMessageBroadcastingStrategy.cs(20,44,20,49): warning CS0649: Field 'IgnoreOwnerPeerMessageBroadcastingStrategy.peers' is never assigned to, and will always have its default value null
19>D:\PSOR\Booma.Library\src\Booma.Instance.Server\Entity\Components\Broadcasting\Common\NetworkTransformBroadcaster.cs(57,16,57,40): warning CS0649: Field 'NetworkTransformBroadcaster.startBroadcastingOnStart' is never assigned to, and will always have its default value false
19>  Booma.Instance.Server -> D:\PSOR\Booma.Library\src\Booma.Instance.Server\bin\Debug\Booma.Instance.Server.dll
25>------ Build started: Project: Booma.Unity.IoCModules.Common, Configuration: Debug Any CPU ------
24>  Booma.Unity.Network.IoCModules.Server -> D:\PSOR\Booma.Library\src\Booma.Unity.Network.IoCModules.Server\bin\Debug\Booma.Unity.Network.IoCModules.Server.dll
23>  Booma.Unity.Network.IoCModules.Client -> D:\PSOR\Booma.Library\src\Booma.Unity.Network.IoCModules.Client\bin\Debug\Booma.Unity.Network.IoCModules.Client.dll
26>------ Build started: Project: Booma.ServerSelection.IoCModules.Client, Configuration: Debug Any CPU ------
27>------ Build started: Project: Booma.Entity.Server, Configuration: Debug Any CPU ------
18>D:\PSOR\Booma.Library\src\Booma.Instance.Client\Entity\GameObject\DefaultGameObjectPrefabEntityFactory.cs(27,39,27,56): warning CS0649: Field 'DefaultGameObjectPrefabEntityFactory.gameobjectFactory' is never assigned to, and will always have its default value null
18>D:\PSOR\Booma.Library\src\Booma.Instance.Client\Entity\GameObject\ClientNetworkDoor.cs(17,22,17,42): warning CS0649: Field 'ClientNetworkDoor.animationControllers' is never assigned to, and will always have its default value null
18>D:\PSOR\Booma.Library\src\Booma.Instance.Client\Entity\Player\ClientNetworkPlayerEntityFactory.cs(17,33,17,47): warning CS0649: Field 'ClientNetworkPlayerEntityFactory.prefabProvider' is never assigned to, and will always have its default value null
18>D:\PSOR\Booma.Library\src\Booma.Instance.Client\Entity\Components\NetworkInteractableEntity.cs(19,32,19,45): warning CS0649: Field 'NetworkInteractableEntity.guidContainer' is never assigned to, and will always have its default value null
18>D:\PSOR\Booma.Library\src\Booma.Instance.Client\Entity\GameObject\ClientNetworkButton.cs(16,20,16,39): warning CS0649: Field 'ClientNetworkButton.animationController' is never assigned to, and will always have its default value null
18>D:\PSOR\Booma.Library\src\Booma.Instance.Client\Entity\Components\PlayerNetworkTransform.cs(17,21,17,36): warning CS0649: Field 'PlayerNetworkTransform.playerTransform' is never assigned to, and will always have its default value null
18>D:\PSOR\Booma.Library\src\Booma.Instance.Client\Entity\Player\ClientNetworkPlayerEntityFactory.cs(20,39,20,56): warning CS0649: Field 'ClientNetworkPlayerEntityFactory.gameobjectFactory' is never assigned to, and will always have its default value null
18>D:\PSOR\Booma.Library\src\Booma.Instance.Client\Peer\NetworkMessageSender.cs(18,29,18,33): warning CS0649: Field 'NetworkMessageSender.peer' is never assigned to, and will always have its default value null
18>  Booma.Instance.Client -> D:\PSOR\Booma.Library\src\Booma.Instance.Client\bin\Debug\Booma.Instance.Client.dll
28>------ Build started: Project: Booma.Combat.Formula.Server.Tests, Configuration: Debug Any CPU ------
27>  Booma.Entity.Server -> D:\PSOR\Booma.Library\src\Booma.Entity.Server\bin\Debug\Booma.Entity.Server.dll
29>------ Build started: Project: Booma.Instance.Handlers.Client, Configuration: Debug Any CPU ------
26>CSC : error CS0006: Metadata file 'D:\PSOR\Booma.Library\src\Booma.ServerSelection.Client\bin\Debug\Booma.ServerSelection.Client.dll' could not be found
30>------ Build started: Project: Booma.Instance.Handlers.Server, Configuration: Debug Any CPU ------
25>  Booma.Unity.IoCModules.Common -> D:\PSOR\Booma.Library\src\Booma.Unity.IoCModules.Common\bin\Debug\Booma.Unity.IoCModules.Common.dll
31>------ Build started: Project: Booma.Instance.IoCModules.Client, Configuration: Debug Any CPU ------
28>  Booma.Combat.Formula.Server.Tests -> D:\PSOR\Booma.Library\test\Booma.Combat.Formula.Server.Tests\bin\Debug\Booma.Combat.Formula.Server.Tests.dll
32>------ Build started: Project: Booma.Instance.IoCModules.Server, Configuration: Debug Any CPU ------
32>  Booma.Instance.IoCModules.Server -> D:\PSOR\Booma.Library\src\Booma.Instance.IoCModules.Server\bin\Debug\Booma.Instance.IoCModules.Server.dll
29>D:\PSOR\Booma.Library\src\Booma.Instance.Handlers.Client\Handlers\GameObjectEntitySpawnEventHandler.cs(21,25,21,31): warning CS0649: Field 'GameObjectEntitySpawnEventHandler.logger' is never assigned to, and will always have its default value null
29>D:\PSOR\Booma.Library\src\Booma.Instance.Handlers.Client\Handlers\PlayerEntitySpawnEventHandler.cs(27,44,27,60): warning CS0649: Field 'PlayerEntitySpawnEventHandler.entityCollection' is never assigned to, and will always have its default value null
29>D:\PSOR\Booma.Library\src\Booma.Instance.Handlers.Client\Handlers\PlayerSpawnResponseHandler.cs(29,39,29,56): warning CS0649: Field 'PlayerSpawnResponseHandler.gameobjectFactory' is never assigned to, and will always have its default value null
29>D:\PSOR\Booma.Library\src\Booma.Instance.Handlers.Client\Handlers\PlayerEntitySpawnEventHandler.cs(24,25,24,31): warning CS0649: Field 'PlayerEntitySpawnEventHandler.logger' is never assigned to, and will always have its default value null
29>D:\PSOR\Booma.Library\src\Booma.Instance.Handlers.Client\Handlers\PlayerSpawnResponseHandler.cs(22,25,22,31): warning CS0649: Field 'PlayerSpawnResponseHandler.logger' is never assigned to, and will always have its default value null
29>D:\PSOR\Booma.Library\src\Booma.Instance.Handlers.Client\Handlers\GameObjectEntitySpawnEventHandler.cs(24,44,24,60): warning CS0649: Field 'GameObjectEntitySpawnEventHandler.entityCollection' is never assigned to, and will always have its default value null
29>D:\PSOR\Booma.Library\src\Booma.Instance.Handlers.Client\Handlers\PlayerEntitySpawnEventHandler.cs(21,41,21,54): warning CS0649: Field 'PlayerEntitySpawnEventHandler.playerFactory' is never assigned to, and will always have its default value null
29>D:\PSOR\Booma.Library\src\Booma.Instance.Handlers.Client\Handlers\PlayerSpawnResponseHandler.cs(26,22,26,34): warning CS0649: Field 'PlayerSpawnResponseHandler.playerPrefab' is never assigned to, and will always have its default value null
29>D:\PSOR\Booma.Library\src\Booma.Instance.Handlers.Client\Handlers\EntityPositionUpdateEventHandler .cs(22,25,22,31): warning CS0169: The field 'EntityPositionUpdateEventHandler.logger' is never used
29>D:\PSOR\Booma.Library\src\Booma.Instance.Handlers.Client\Handlers\GameObjectEntitySpawnEventHandler.cs(27,51,27,64): warning CS0649: Field 'GameObjectEntitySpawnEventHandler.objectFactory' is never assigned to, and will always have its default value null
29>  Booma.Instance.Handlers.Client -> D:\PSOR\Booma.Library\src\Booma.Instance.Handlers.Client\bin\Debug\Booma.Instance.Handlers.Client.dll
33>------ Build started: Project: Booma.Entity.SectionId.Calculator, Configuration: Debug Any CPU ------
34>------ Build started: Project: Booma.Payloads.Tests, Configuration: Debug Any CPU ------
34>  Booma.Payloads.Tests -> D:\PSOR\Booma.Library\test\Booma.Payloads.Tests\bin\Debug\Booma.Payloads.Tests.dll
35>------ Build started: Project: Booma.ServerSelection.Handlers.Client, Configuration: Debug Any CPU ------
30>D:\PSOR\Booma.Library\src\Booma.Instance.Handlers.Server\Handlers\EntityInteractionRequestPayloadHandler.cs(22,44,22,60): warning CS0649: Field 'EntityInteractionRequestPayloadHandler.entityCollection' is never assigned to, and will always have its default value null
30>D:\PSOR\Booma.Library\src\Booma.Instance.Handlers.Server\Handlers\PlayerSpawnRequestPayloadHandler.cs(33,44,33,60): warning CS0649: Field 'PlayerSpawnRequestPayloadHandler.entityCollection' is never assigned to, and will always have its default value null
30>D:\PSOR\Booma.Library\src\Booma.Instance.Handlers.Server\Handlers\PlayerSpawnRequestPayloadHandler.cs(40,40,40,57): warning CS0649: Field 'PlayerSpawnRequestPayloadHandler.entityGuidFactory' is never assigned to, and will always have its default value null
30>D:\PSOR\Booma.Library\src\Booma.Instance.Handlers.Server\Handlers\EntityInteractionRequestPayloadHandler.cs(25,51,25,68): warning CS0649: Field 'EntityInteractionRequestPayloadHandler.guidLookupService' is never assigned to, and will always have its default value null
30>D:\PSOR\Booma.Library\src\Booma.Instance.Handlers.Server\Handlers\EntityInteractionRequestPayloadHandler.cs(19,25,19,31): warning CS0649: Field 'EntityInteractionRequestPayloadHandler.logger' is never assigned to, and will always have its default value null
30>D:\PSOR\Booma.Library\src\Booma.Instance.Handlers.Server\Handlers\PlayerSpawnRequestPayloadHandler.cs(27,41,27,60): warning CS0649: Field 'PlayerSpawnRequestPayloadHandler.playerEntityFactory' is never assigned to, and will always have its default value null
30>D:\PSOR\Booma.Library\src\Booma.Instance.Handlers.Server\Handlers\PlayerMoveRequestPayloadHandler.cs(22,44,22,60): warning CS0649: Field 'PlayerMoveRequestPayloadHandler.entityCollection' is never assigned to, and will always have its default value null
30>D:\PSOR\Booma.Library\src\Booma.Instance.Handlers.Server\Handlers\PlayerMoveRequestPayloadHandler.cs(19,51,19,68): warning CS0649: Field 'PlayerMoveRequestPayloadHandler.guidLookupService' is never assigned to, and will always have its default value null
30>D:\PSOR\Booma.Library\src\Booma.Instance.Handlers.Server\Handlers\PlayerSpawnRequestPayloadHandler.cs(36,36,36,50): warning CS0649: Field 'PlayerSpawnRequestPayloadHandler.peerCollection' is never assigned to, and will always have its default value null
30>D:\PSOR\Booma.Library\src\Booma.Instance.Handlers.Server\Handlers\PlayerSpawnRequestPayloadHandler.cs(43,46,43,64): warning CS0649: Field 'PlayerSpawnRequestPayloadHandler.connectionRegistry' is never assigned to, and will always have its default value null
30>  Booma.Instance.Handlers.Server -> D:\PSOR\Booma.Library\src\Booma.Instance.Handlers.Server\bin\Debug\Booma.Instance.Handlers.Server.dll
31>  Booma.Instance.IoCModules.Client -> D:\PSOR\Booma.Library\src\Booma.Instance.IoCModules.Client\bin\Debug\Booma.Instance.IoCModules.Client.dll
35>CSC : error CS0006: Metadata file 'D:\PSOR\Booma.Library\src\Booma.ServerSelection.Client\bin\Debug\Booma.ServerSelection.Client.dll' could not be found
33>  Booma.Entity.SectionId.Calculator -> D:\PSOR\Booma.Library\src\Booma.Entity.SectionId.Calculator\bin\Debug\Booma.Entity.SectionId.Calculator.dll
========== Build: 32 succeeded, 3 failed, 1 up-to-date, 0 skipped ==========

I would copy the other errors I'm getting (after the one in the title) but I don't know how to copy all the errors without manually doing it.

Anyway, have I done everything right so far? Any idea why I'm getting this error? Any help is appreciated.

Thanks for taking the time to read this.

**Comment by HelloKitty** [comment] 2017-05-15 17:33
@CyanPrime Interesting, Fasterflect is a library that is available on the official Nuget feed. I do host my own fork of Fasterflect but it shouldn't be used in this project. I cannot determine what is wrong from that log. I'll have to clone it somewhere clean and check out what might be wrong locally.

Also, on an unrelated note I'm working on extending the documentation in the ReadMe and I welcome feedback from outsider contributors. I need to know if there are gaps or unclear statements in there. I'm interested in extending it so that the difficult parts of the project can be better understood.

**Comment by HelloKitty** [comment] 2017-05-15 17:41
@CyanPrime I just downloaded the source and rebuilt it and it worked just fine. My suggestions would be to clean and rebuild the solution. I can't identify an issue. Maybe try to update and install Nuget v3? It sounds like the nuget packages aren't being restored but I can't identify why.

Vs2017
HelloKitty nuget source: https://www.myget.org/F/hellokitty/api/v2
Nuget v3

That is all I can think of that might be issues. You use Vs2017 and added the nuget source so it's possible it's Nuget v3? I'm very interested in identifying what the issue is so we can update the ReadMe for future contributors who want to build the solution.

**Comment by HelloKitty** [comment] 2017-05-15 17:54
@CyanPrime Let me know if installing Nuget v3 had any effect or if rebuilding fixed the issue?

**Comment by CyanPrime** [comment] 2017-05-15 17:58
@HelloKitty Strangely enough I downloaded a extendtion to be able to copy all the errors I had gotten, and reloaded VS and did another build of Booma.Library, and it built fine.  No errors at all.
I'm getting some warnings like
Severity	Code	Description	Project	File	Line	Suppression State
Warning	CS0649	Field 'AuthenticationWebClient.OnConnected' is never assigned to, and will always have its default value null	Booma.ServerSelection.Client	D:\PSOR\Booma.Library\src\Booma.ServerSelection.Client\Clients\AuthenticationWebClient.cs	26	Active

But that's it. I guess it was on my side? I don't know how I fixed it though except for restarting VS2017.

On an unrelated note: Is there a better place to contact you? I'd like to get more involved with this project.

**Comment by HelloKitty** [comment] 2017-05-15 18:28
@CyanPrime Hmmm that's odd, glad it resolved itself though. You're the first person other than myself to try to build this new solution I created last week.

As for the warning, if you go to [the class field it points to](https://github.com/BoomaNation/Booma.Library/blob/a04c718318fb5c770615019c890ad4e1c5bcb5b9/src/Booma.ServerSelection.Client/Clients/AuthenticationWebClient.cs) you can see it says that OnConnected will always be null. This is possible, but incorrect. Unity3D allows you modify fields in the editor. Booma.Library relies on Unity3D's serialization to the editor, GladBehaviour's Interface serialization and SceneJect's property injection for dependencies using [Inject]. These cases will lead to Visual Studio mislabeling fields as always null. Warnings for that can be ignored.

The best way to currently contact me is by raising an issue on Github. While we do have a slack for communicating internally the project has mostly been dormant and there hasn't been any collaboration for some time.

Once the documentation for this project is finished, the library is cleaned up and some existing faults are fixed and other missing pieces are added I'll try to restart the organized collaboration initiative.

Since this issue is fixed I will be closing it.

**Closed by HelloKitty** 2017-05-15 18:28 UTC
